# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:03
from __future__ import unicode_literals

import adminsortable.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Asset', max_length=140)),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
                ('duration', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(5)], verbose_name='Duration (s)')),
                ('active', models.BooleanField(default=True)),
                ('asset_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['asset_order'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('name', models.CharField(default='Unnamed Device', max_length=128)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Playlist', max_length=140, unique=True)),
                ('playlist_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['playlist_order'],
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signage.Playlist'),
        ),
        migrations.AddField(
            model_name='asset',
            name='playlist',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signage.Playlist'),
        ),
    ]
