# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_auto_20160910_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
