# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_auto_20160905_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='alert',
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
