# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_device_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('web', 'Web Page'), ('video', 'Video (MP4)')], default='web', max_length=8, verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', editable=False, max_length=45, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Seen'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default='00:de:ad:be:ef:42', editable=False, max_length=17, unique=True, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Unnamed Device', max_length=128, verbose_name='Device Name'),
        ),
    ]
