# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_auto_20160910_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signage.Playlist')),
                ('active', models.BooleanField(default=False)),
                ('devices', models.ManyToManyField(to='signage.Device')),
            ],
            options={
                'verbose_name_plural': 'Alerts',
            },
            bases=('signage.playlist',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='duration',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(5)], verbose_name='Duration (s)'),
        ),
    ]
