# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0005_auto_20160910_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='when',
            field=models.DateTimeField(auto_now=True, verbose_name='At'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Untitled', max_length=140, unique=True),
        ),
    ]
