# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0006_auto_20160910_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='shown_on',
            field=models.ManyToManyField(editable=False, related_name='shown_on', to='signage.Device'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start At'),
        ),
    ]
