# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 10:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0008_asset_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parameters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.CharField(max_length=512, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
    ]
