# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0010_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='PredefinedAsset',
        ),
        migrations.AlterModelOptions(
            name='predefinedasset',
            options={'verbose_name': 'Predefined Asset', 'verbose_name_plural': 'Predefined Assets'},
        ),
    ]
