# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0011_auto_20160911_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='when',
            field=models.DateTimeField(verbose_name='Start At'),
        ),
    ]
